[FIO toup] imx8mq_evk: set bootm len to 64
Allow larger bootm images (required by LmP).

Fixes:
   Uncompressing Kernel Image
Error: inflate() returned -5
Image too large: increase CONFIG_SYS_BOOTM_LEN
Must RESET board to recover

Signed-off-by: Michael Scott <mike@foundries.io>