[FIO temphack] colibri_imx7_emmc: fix linking mxsfb driver
video_link library is required for mxsfb driver. Since
CONFIG_VIDEO_MXS is not converted to Kconfig, VIDEO_LINK can't be
selected automatically. Select the option VIDEO_LINK manually to fix
linkage error [1].

[1]
drivers/built-in.o: in function `mxs_of_get_timings':
drivers/video/mxsfb.c:487: undefined reference to `video_link_get_next_device'
drivers/video/mxsfb.c:489: undefined reference to `video_link_get_display_timings'

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>