[FIO toimx] ARM: mx6: check the need to build module_fuse in SPL/TPL
This fixes the compiler error [1].

[1]
arch/arm/mach-imx/mx6/module_fuse.c:253:5: error: redefinition of ‘check_module_fused’
  253 | u32 check_module_fused(enum fuse_module_type module)
      |     ^~~~~~~~~~~~~~~~~~
In file included from ./arch/arm/include/asm/mach-imx/sys_proto.h:13,
                 from ./arch/arm/include/asm/arch/sys_proto.h:10,
                 from arch/arm/mach-imx/mx6/module_fuse.c:9:
./arch/arm/include/asm/mach-imx/module_fuse.h:78:19: note: previous definition of ‘check_module_fused’ was here

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>